language: go

go:
  - 1.6
  - 1.7
  - 1.8
  - tip

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

before_install:
  - go get github.com/golang/lint/golint

script:
  - golint ./...
  - go vet ./...